In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

$r_{m}\ =\ \alpha_{0}\ -\ {\frac{\alpha_{1}\beta_{0}}{\mu_{m}-\alpha_{0}}}$

In [11]:
n = 5
mu = np.array([1.1, 1.15, 1.20, 1.27, 1.3]).reshape(-1, 1)
cov = [[0.01, 0.0007 , 0, 0, 0.0006], [0.0007, 0.05 , 0.0001, 0, 0], [0, 0.0001 , 0.07, 0, 0], [0, 0 , 0, 0.08, 0], [0.0006, 0 , 0, 0, 0.09]]
l = np.ones(n).reshape(-1, 1)
r = 1.02

In [12]:
cov

[[0.01, 0.0007, 0, 0, 0.0006],
 [0.0007, 0.05, 0.0001, 0, 0],
 [0, 0.0001, 0.07, 0, 0],
 [0, 0, 0, 0.08, 0],
 [0.0006, 0, 0, 0, 0.09]]

In [13]:
h0 = (np.linalg.inv(cov) @ l) / (np.transpose(l) @ np.linalg.inv(cov) @ l)
h0

array([[0.63729589],
       [0.1208592 ],
       [0.09266068],
       [0.08122917],
       [0.06795506]])

In [16]:
h1 = np.linalg.inv(cov) @ mu - (np.transpose(l) @ np.linalg.inv(cov) @ mu) * h0
h1

array([[-4.39191429],
       [ 0.20567052],
       [ 0.81814905],
       [ 1.59113751],
       [ 1.77695721]])

In [17]:
a0 = np.transpose(mu) @ h0
a0

array([[1.142709]])

In [19]:
a1 = np.transpose(mu) @ h1
a1

array([[0.71798325]])

In [18]:
b0 = np.transpose(h0) @ cov @ h0
b0

array([[0.00649833]])

In [21]:
b1 = np.transpose(h0) @ cov @ h1
b1

array([[-5.20417043e-17]])

In [20]:
b2 = np.transpose(h1) @ cov @ h1
b2

array([[0.71798325]])

In [23]:
# Implied rf
a0 - (a1 @ b0) / (1.4 - a0)

array([[1.12457508]])

$\mu_{m}\ =\ \alpha_{0}\ +\ \frac{\alpha_{1}\beta_{0}}{\alpha_{0}-r_{m}}$

In [24]:
a0 + (a1 @ b0) / (a0 - 1.05)

array([[1.19303523]])